export const MOCK_TRAILS = {
  facil: [
    {
      id: 'f1',
      title: 'Trilha do Lemos',
      author: 'Riassa Mara',
      time: '1 hr',
      distance: '2km',
      rating: '4.4',
      reviews: '90',
      difficulty: 'Fácil',
      image: require('../assets/trilhas/lemos.jpg'),
    },
    {
      id: 'f2',
      title: 'Pedra do Cruzeiro',
      author: 'Carlos Silva',
      time: '10 min',
      distance: '300m',
      rating: '4.5',
      reviews: '200',
      difficulty: 'Fácil',
      image: require('../assets/trilhas/pedra-cruzeiro.jpg'),
    },
  ],
  medio: [
    {
      id: 'm1',
      title: 'Vale Perdido',
      author: 'João Lucas',
      time: '2 hr',
      distance: '4km',
      rating: '4.8',
      reviews: '150',
      difficulty: 'Médio',
      image: require('../assets/trilhas/vale-perdido.jpg'),
    },
    {
      id: 'm2',
      title: 'Trilha da Cabeça da Bruxa',
      author: 'Carlos Silva',
      time: '22 min',
      distance: '0,8km',
      rating: '4.2',
      reviews: '85',
      difficulty: 'Médio',
      image: require('../assets/trilhas/cabeca-bruxa.jpg'),
    },
  ],
  dificil: [
    {
      id: 'd1',
      title: 'Trilha da Cabeça da Bruxa',
      author: 'Carlos Silva',
      time: '22 min',
      distance: '0,8km',
      rating: '3.5',
      reviews: '45',
      difficulty: 'Difícil',
      image: require('../assets/trilhas/cabeca-bruxa.jpg'),
    },
    {
      id: 'd2',
      title: 'Vale Perdido',
      author: 'João Lucas',
      time: '2 hr',
      distance: '4km',
      rating: '4.1',
      reviews: '190',
      difficulty: 'Difícil',
      image: require('../assets/trilhas/vale-perdido.jpg'),
    },
  ],
};
